#!/bin/bash


#basic funtion for cancel button
function quitCheck {
  if [ $? = 1 ]; then
	exit
  fi
}

#ANS is the path to file. $1 is the file you click. 
#We use printf.... instead of a simple pwd just for the case of the space charachter in folder's name. 
ANS=`printf "%q\n" "$(pwd)"`/$1

#take the real name of application
REALNAME=`zenity --entry --text="Please enter the name of the application (no need to be the same with executive). Please DON'T use spaces." --title="Choose Name"`
quitCheck


#take the executive name (last part of ANS)
IFS="/"
temp=($ANS)
COUNT=`grep -o "/" <<<"$ANS" | wc -l`
NAME=${temp[$COUNT]} 

name_count=${#NAME}
#remove executive name from ANS
IFS=""
for ((i=0;i<$name_count;i++))
do
	ANS=`echo "${ANS%?}"`
done

#create executive file (temporary for now)
echo "cd $ANS" > $REALNAME.smyc
echo " " >> $REALNAME.smyc
echo "chmod +x $NAME" >> $REALNAME.smyc
echo "./$NAME" >> $REALNAME.smyc
echo "java -jar $NAME" >> $REALNAME.smyc


#take icon location
zenity --info --title="Install It" --text="Select an icon"
quitCheck
ICON=`zenity --file-selection --title="Select Icon"`
quitCheck

#take password
PASS=$(zenity --password --title="Give your sudo password")
quitCheck

#Copy icon to /usr/share/pixmaps
echo "echo $PASS | sudo -S cp $ICON /usr/share/pixmaps" > temp
xterm -e bash temp


#Move generated executive to /usr/bin
echo "echo $PASS | sudo -S mv $REALNAME.smyc /usr/bin" > temp
xterm -e bash temp

#Make it executalbe
echo "echo  $PASS | sudo -S chmod +x /usr/bin/$REALNAME.smyc" > temp
xterm -e bash temp

#take icon name (last part of ICON)
IFS="/"
temp=($ICON)
COUNT=`grep -o "/" <<<"$ICON" | wc -l`
ICON_NAME=${temp[$COUNT]} 


#Create .desktop file
 echo "[Desktop Entry]" > $REALNAME.desktop
	    echo >> $REALNAME.desktop
	    echo Name="$REALNAME" >> $REALNAME.desktop
	    echo >> $REALNAME.desktop 
	    echo Exec="\"$REALNAME.smyc\"" >> $REALNAME.desktop
	    echo >> $REALNAME.desktop
	    echo Type="Application" >> $REALNAME.desktop
	    echo Icon=/usr/share/pixmaps/$ICON_NAME >> $REALNAME.desktop
	    echo >> $REALNAME.desktop 

#move .desktop file to /usr/share/applications
echo "echo $PASS | sudo -S mv "$REALNAME.desktop" /usr/share/applications" > temp
xterm -e bash temp

rm temp

echo "$REALNAME" >> ~/.InstallerCreator


notify-send "$REALNAME installed succesfuly!"
