######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 8 16:14:23 2014
######################################################################

TEMPLATE = app
TARGET = 
QT += core gui
QT += widgets
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
